export const Actions = {
  GET_ITEMS: "GET_ITEMS",
  APPEND_ITEMS: "APPEND_ITEMS",
  GET_ITEMS_ID: "GET_ITEMS_ID",
  GET_ITEMS_CREATE: "GET_ITEMS_CREATE",
  GET_ITEMS_UPDATE: "GET_ITEMS_UPDATE",
  GET_ITEM_DELETE: "GET_ITEM_DELETE",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
};
